sudo: false
dist: xenial
language: node_js
node_js:
  - 12
cache: npm

before_install:
  - sudo apt-get install -y calibre libfontconfig
  - npm install -g gitbook-cli svgexport@0.3.2

before_script:
  - npm install
  - export PATH=$(npm bin):$PATH
  - gitbook install

script:
  - gitbook build . --gitbook=3.2.3
  - gitbook pdf . --gitbook=3.2.3
  - mv book.pdf _book/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _book
  on:
    branch: master
