sudo: false
dist: xenial
language: node_js
node_js:
  - 12
cache: npm

addons:
  apt:
    packages:
      - calibre
      - libfontconfig
      # Japanese
      - language-pack-ja
      - japan*
      # Chinese
      - language-pack-zh*
      - chinese*
      # Korean
      - language-pack-ko
      - korean*
      # Fonts
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core

before_install:
  - npm install -g gitbook-cli svgexport@0.3.2

before_script:
  - npm install
  - export PATH=$(npm bin):$PATH
  - gitbook install

script:
  - gitbook build . --gitbook=3.2.3
  - gitbook pdf . --gitbook=3.2.3
  - mv book.pdf _book/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _book
  on:
    branch: master
